listening-port=3478
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=${TURN_SHARED_SECRET}
realm=${TURN_REALM}
server-name=${TURN_REALM}
no-multicast-peers
no-cli
no-tls
no-dtls
min-port=49160
max-port=49200
log-file=stdout
simple-log
